import base64
import os

class Helper(object):
    def __init__(self):
        pass

    """
    Get Application Name
    """
    def getAppName(self):
        return "Grazioso Salvare Dashboard"
    
    """
    Get Url
    """
    def getUrl(self):
        return "https://www.snhu.edu/"

    """
    Get Encoded Logo Image
    """
    def getImage(self):
        image_filename = 'Grazioso_Salvare_Logo.png'
        encoded_image  = ""
        if not os.path.exists(image_filename):
            print(f"WARNING: Logo file '{image_filename}' not found.")
            encoded_image = b""
        else:
            encoded_image = base64.b64encode(open(image_filename, 'rb').read())
        return encoded_image
    
    #############################################
    # Check string value if it's NOT valid string
    # return message Otherwise return string
    #############################################
    def check_and_replace(self, string, message):
        if string is None or len(string) == 0:
            return message
        return string
    
    def getCoulmnMapping(self):
        
        return {
            'outcome_subtype':'Outcome Subtype',
            "outcome_type":'Outcome Type',
            "name":'Name',
            '_id':'#',
            'animal_id':'Id',
            "date_of_birth":'Date Of Birth',
            'datetime':'Date-time', 
            'monthyear':'Month Year',
            'name': 'Animal Name',
            "age_upon_outcome":"Age",
            'animal_type': 'Type',
            'age_upon_outcome_in_weeks':'Age Upon Outcome',
            'breed': 'Breed',
            'color': 'Color',
            'location_lat': 'Latitude',
            'location_long': 'Longitude',
        }
    

    def animal_breed(self):
        return  [
             '----------',
            'Domestic Shorthair Mix',
            'Chihuahua Shorthair Mix',
            'Siamese Mix',
            'Labrador Retriever Mix',
            'Cardigan Welsh Corgi Mix',
            'Pit Bull Mix',
            'Labrador Retriever/Australian Cattle Dog',
            'Dachshund Wirehair Mix',
            'Boxer/Bullmastiff',
            'Miniature Schnauzer Mix',
            'Domestic Medium Hair Mix',
            'American Bulldog Mix',
            'Dachshund/Chihuahua Shorthair',
            'Maltese Mix',
            'Australian Cattle Dog Mix',
            'Dachshund Mix',
            'Miniature Poodle Mix',
            'Pug/Chihuahua Shorthair',
            'German Shepherd/Labrador Retriever',
            'Siberian Husky Mix',
            'Australian Cattle Dog/Beagle',
            'Yorkshire Terrier Mix',
            'Miniature Poodle',
            'Beagle Mix',
            'Chow Chow Mix',
            'Chinese Sharpei Mix',
            'Chinese Crested Mix',
            'Staffordshire Mix',
            'Border Collie/Queensland Heeler',
            'German Shepherd Mix',
            'Chihuahua Shorthair',
            'Raccoon Mix',
            'Raccoon',
            'Beagle',
            'Chihuahua Longhair/Yorkshire Terrier',
            'Bat',
            'Queensland Heeler Mix',
            'Flat Coat Retriever Mix',
            'Pointer Mix',
            'Domestic Longhair Mix',
            'Scottish Terrier Mix',
            'Boxer/Queensland Heeler',
            'Catahoula Mix',
            'Great Pyrenees Mix',
            'Boxer Mix',
            'Domestic Shorthair',
            'Armadillo Mix',
            'Dachshund Longhair Mix',
            'Bat Mix',
            'English Bulldog Mix',
            'Jack Russell Terrier Mix',
            'Fox Mix',
            'Chihuahua Shorthair/Rat Terrier',
            'Australian Kelpie Mix',
            'Miniature Pinscher Mix',
            'Miniature Schnauzer/Jack Russell Terrier',
            'Australian Shepherd Mix',
            'Blue Lacy',
            'Labrador Retriever/Pit Bull',
            'Rex Mix',
            'Labrador Retriever/Doberman Pinsch',
            'Rottweiler/Labrador Retriever',
            'German Shepherd/Doberman Pinsch',
            'Yorkshire Terrier/Yorkshire Terrier',
            'Great Dane Mix',
            'Pomeranian Mix',
            'Carolina Dog Mix',
            'Rat Terrier Mix',
            'Golden Retriever',
            'Labrador Retriever/German Shepherd',
            'Whippet/Plott Hound',
            'Pekingese Mix',
            'Brittany Mix',
            'American BullDog',
            'Scottish Terrier',
            'Rhod Ridgeback Mix',
            'Rottweiler Mix',
            'Australian Cattle Dog/Chow Chow',
            'French BullDog',
            'Dutch Shepherd Mix',
            'Great Pyrenees/Pointer',
            'Wire Hair Fox Terrier Mix',
            'Labrador Retriever/Staffordshire',
            'Redbone Hound Mix',
            'Rhode Island Mix',
            'Australian Cattle Dog/German Shepherd',
            'Chihuahua Longhair Mix',
            'German Shepherd',
            'Pit Bull',
            'Rabbit Sh Mix',
            'Opossum',
            'Bull Terrier Mix',
            'Squirrel Mix',
            'Swiss Hound/Pit Bull',
            'Duck',
            'Boston Terrier',
            'American Pit Bull Terrier Mix',
            'Anatol Shepherd Mix',
            'American Shorthair Mix',
            'Mastiff/Plott Hound',
            'Australian Cattle Dog/German Shorthair Pointer',
            'Border Collie Mix',
            'Maine Coon Mix',
            'Australian Shepherd/Labrador Retriever',
            'Labrador Retriever/Chow Chow',
            'Black Mouth Cur/Blue Lacy',
            'Shih Tzu/Border Terrier',
            'Golden Retriever Mix',
            'Snowshoe Mix',
            'Shih Tzu Mix',
            'Border Collie/Great Pyrenees',
            'Plott Hound Mix',
            'Dachshund',
            'Border Collie/American Staffordshire Terrier',
            'American Bulldog/Labrador Retriever',
            'Opossum Mix',
            'Rottweiler',
            'Pug Mix',
            'German Shepherd/Alaskan Malamute',
            'Yorkshire Terrier',
            'Chihuahua Shorthair/Italian Greyhound',
            'Queensland Heeler',
            'Chihuahua Shorthair/Wire Hair Fox Terrier',
            'Treeing Walker Coonhound Mix',
            'Ragdoll Mix',
            'Pomeranian/Border Terrier',
            'Dachshund/Labrador Retriever',
            'Miniature Pinscher',
            'Snowshoe',
            'Mexican Hairless Mix',
            'Black Mouth Cur',
            'Labrador Retriever',
            'Catahoula/Pit Bull',
            'Pbgv',
            'Akita Mix',
            'Labrador Retriever/Blue Lacy',
            'Boxer/Pit Bull',
            'Pomeranian/Chihuahua Longhair',
            'Guinea Pig Mix',
            'Border Collie',
            'English BullDog',
            'Manchester Terrier Mix',
            'Jack Russell Terrier',
            'Bearded Collie Mix',
            'American Pit Bull Terrier/Labrador Retriever',
            'Pit Bull/Boxer',
            'Mastiff Mix',
            'Doberman Pinsch',
            'BullDog',
            'Yorkshire Terrier/Pomeranian',
            'American Staffordshire Terrier/Australian Cattle Dog',
            'Boston Terrier Mix',
            'Doberman Pinsch Mix',
            'Labrador Retriever/Beagle',
            'Basset Hound Mix',
            'Cocker Spaniel',
            'Staffordshire/Labrador Retriever',
            'Wire Hair Fox Terrier/Dachshund',
            'Doberman Pinsch/Australian Cattle Dog',
            'Pbgv Mix',
            'Belgian Malinois Mix',
            'Pit Bull/Pug',
            'Chihuahua Shorthair/Dachshund',
            'Tibetan Spaniel Mix',
            'American Eskimo/Alaskan Husky',
            'Miniature Schnauzer/Miniature Poodle',
            'Guinea Pig',
            'Irish Terrier/Labrador Retriever',
            'Netherlnd Dwarf Mix',
            'Cairn Terrier/Yorkshire Terrier',
            'Angora Mix',
            'American Staffordshire Terrier Mix',
            'Domestic Longhair',
            'Labrador Retriever/Plott Hound',
            'Pomeranian/Cocker Spaniel',
            'Grackle Mix',
            'Labrador Retriever/Pointer',
            'Hawk',
            'Bichon Frise Mix',
            'Domestic Shorthair/British Shorthair',
            'Cardigan Welsh Corgi',
            'Labrador Retriever/Basset Hound',
            'Dalmatian Mix',
            'Lionhead',
            'Labrador Retriever/Pembroke Welsh Corgi',
            'New Zealand Wht Mix',
            'Boerboel Mix',
            'Cairn Terrier Mix',
            'Black Mouth Cur Mix',
            'Black/Tan Hound Mix',
            'Pixiebob Shorthair Mix',
            'English Coonhound',
            'Pointer/Border Collie',
            'Blue Lacy Mix',
            'Labrador Retriever/Vizsla',
            'Yorkshire Terrier/Chihuahua Longhair',
            'Lop-English Mix',
            'Boxer',
            'Dachshund Wirehair/Chihuahua Longhair',
            'Muscovy',
            'Balinese Mix',
            'Golden Retriever/Border Collie',
            'Australian Cattle Dog',
            'Catahoula/Staffordshire',
            'Rhod Ridgeback/Pit Bull',
            'Hotot Mix',
            'Rabbit Lh Mix',
            'Jack Russell Terrier/Chihuahua Shorthair',
            'Manchester Terrier/Chihuahua Shorthair',
            'Pointer',
            'Catahoula/Plott Hound',
            'Bernese Mountain Dog Mix',
            'Skunk Mix',
            'Black/Tan Hound',
            'Whippet Mix',
            'Siberian Husky',
            'Australian Shepherd/German Shepherd',
            'Dachshund/Manchester Terrier',
            'Patterdale Terr Mix',
            'Pekingese',
            'Soft Coated Wheaten Terrier Mix',
            'Parakeet',
            'Newfoundland/Labrador Retriever',
            'American Eskimo Mix',
            'Labrador Retriever/Smooth Fox Terrier',
            'Pointer/Pit Bull',
            'Chicken Mix',
            'Great Dane/Labrador Retriever',
            'Cocker Spaniel Mix',
            'German Shepherd/Pit Bull',
            'English Foxhound',
            'Lionhead Mix',
            'Snake Mix',
            'Labrador Retriever/Labrador Retriever',
            'Smooth Fox Terrier Mix',
            'Miniature Schnauzer',
            'Basenji/Jack Russell Terrier',
            'Labrador Retriever/Boxer',
            'Himalayan Mix',
            'Toy Poodle Mix',
            'Bull Terrier',
            'Irish Setter/Pit Bull',
            'Norfolk Terrier Mix',
            'Labrador Retriever/Great Dane',
            'Anatol Shepherd/Border Collie',
            'Chihuahua Longhair/Cardigan Welsh Corgi',
            'Great Pyrenees/Labrador Retriever',
            'Lhasa Apso Mix',
            'Australian Terrier Mix',
            'Boxer/Catahoula',
            'Rat Terrier',
            'Lhasa Apso/Pbgv',
            'Basenji Mix',
            'Russian Blue Mix',
            'Parson Russell Terrier Mix',
            'American Staffordshire Terrier',
            'Belgian Hare',
            'Chihuahua Shorthair/Cairn Terrier',
            'Dutch Shepherd/Boxer',
            'Border Collie/German Shepherd',
            'Silky Terrier Mix',
            'Boston Terrier/Dachshund',
            'German Shepherd/German Shepherd',
            'Dogo Argentino Mix',
            'Bengal Mix',
            'Skunk',
            'Schnauzer Giant Mix',
            'Basenji',
            'Manchester Terrier/Dachshund',
            'Cardigan Welsh Corgi/Chihuahua Shorthair',
            'Beagle/Labrador Retriever',
            'English Spot Mix',
            'Vizsla Mix',
            'Cavalier Span/Chihuahua Longhair',
            'Collie Rough Mix',
            'Miniature Poodle/English Cocker Spaniel',
            'Maltese',
            'Rat Terrier/Chihuahua Shorthair',
            'Shih Tzu',
            'Jack Russell Terrier/Yorkshire Terrier',
            'English Coonhound Mix',
            'Domestic Medium Hair',
            'Labrador Retriever/Border Collie',
            'Havanese',
            'Catahoula/Alaskan Husky',
            'Persian Mix',
            'Jack Russell Terrier/Shih Tzu',
            'Alaskan Husky Mix',
            'Boxer/Staffordshire',
            'Norwich Terrier Mix',
            'Rat',
            'Chesa Bay Retr Mix',
            'Parson Russell Terrier/Beagle',
            'Jack Russell Terrier/Pembroke Welsh Corgi',
            'Bloodhound Mix',
            'Miniature Schnauzer/Cairn Terrier',
            'Plott Hound/Mastiff',
            'Cairn Terrier',
            'St. Bernard Smooth Coat/Anatol Shepherd',
            'Plott Hound/Labrador Retriever',
            'Border Terrier Mix',
            'Golden Retriever/Whippet',
            'Pug/Beagle',
            'Squirrel',
            'St. Bernard Rough Coat Mix',
            'Great Pyrenees/Golden Retriever',
            'Catahoula/Labrador Retriever',
            'German Shepherd/Black/Tan Hound',
            'English Pointer Mix',
            'American Bulldog/Basset Hound',
            'Collie Smooth Mix',
            'Great Dane',
            'Shih Tzu/Toy Poodle',
            'Shetland Sheepdog Mix',
            'German Shorthair Pointer Mix',
            'Labrador Retriever/Border Terrier',
            'Staffordshire/Bull Terrier',
            'Dachshund/Rat Terrier',
            'German Shorthair Pointer',
            'Anatol Shepherd',
            'Newfoundland Mix',
            'Siberian Husky/Anatol Shepherd',
            'Chow Chow',
            'Rat Terrier/Labrador Retriever',
            'Miniature',
            'German Wirehaired Pointer',
            'English Foxhound Mix',
            'Anatol Shepherd/Great Pyrenees',
            'Pembroke Welsh Corgi Mix',
            'Siberian Husky/Labrador Retriever',
            'Chihuahua Shorthair/Jack Russell Terrier',
            'Dachshund/Australian Cattle Dog',
            'Australian Cattle Dog/Labrador Retriever',
            'Maltese/Miniature Poodle',
            'Lhasa Apso',
            'Pit Bull/Chow Chow',
            'Catahoula/Australian Cattle Dog',
            'Miniature Poodle/Miniature Schnauzer',
            'Great Pyrenees',
            'Munchkin Longhair Mix',
            'Labrador Retriever/Newfoundland',
            'Basenji/Australian Cattle Dog',
            'Toy Fox Terrier Mix',
            'Norwich Terrier/Yorkshire Terrier',
            'Cockatiel Mix',
            'Norfolk Terrier/Border Terrier',
            'Pit Bull/Chinese Sharpei',
            'Labrador Retriever/Queensland Heeler',
            'Border Collie/Catahoula',
            'Bulldog Mix',
            'Landseer Mix',
            'Bull Terrier Miniature Mix',
            'Dutch/Rabbit Sh',
            'Labrador Retriever/Chesa Bay Retr',
            'Chihuahua Longhair/Dachshund Wirehair',
            'Labrador Retriever/Flat Coat Retriever',
            'Mastiff/Boxer',
            'Leonberger Mix',
            'Weimaraner',
            'Chihuahua Shorthair/Parson Russell Terrier',
            'Harrier Mix',
            'Airedale Terrier Mix',
            'Miniature Pinscher/Chihuahua Shorthair',
            'American Bulldog/Pit Bull',
            'Japanese Bobtail Mix',
            'Chihuahua Shorthair/Pekingese',
            'Cardigan Welsh Corgi/Miniature Pinscher',
            'Jack Russell Terrier/Australian Cattle Dog',
            'Pointer/Catahoula',
            'St. Bernard Smooth Coat Mix',
            'American Staffordshire Terrier/Labrador Retriever',
            'Weimaraner Mix',
            'West Highland/Toy Fox Terrier',
            'Catahoula/Chow Chow',
            'Chihuahua Shorthair/Shiba Inu',
            'Pointer/Anatol Shepherd',
            'Cocker Spaniel/Labrador Retriever',
            'Whippet/Beagle',
            'Lhasa Apso/Miniature Poodle',
            'Chihuahua Longhair/Cairn Terrier',
            'Dachshund/Beagle',
            'Chihuahua Shorthair/German Shepherd',
            'Alaskan Malamute/Labrador Retriever',
            'Miniature Schnauzer/Chihuahua Shorthair',
            'Labrador Retriever/English Springer Spaniel'
            'Swedish Vallhund Mix',
            'Anatol Shepherd/Mastiff'
            'Pointer/Labrador Retriever',
            'Samoyed',
            'Chihuahua Shorthair/Cocker Spaniel',
            'Labrador Retriever/Australian Kelpie',
            'Australian Kelpie',
            'Staffordshire/Australian Cattle Dog',
            'Cavalier Span Mix',
            'Blue Lacy/Australian Cattle Dog',
            'Australian Kelpie/Miniature Pinscher',
            'German Shepherd/Boxer',
            'Black Mouth Cur/Siberian Husky',
            'Basset Hound',
            'Labrador Retriever/Australian Shepherd',
            'Siamese',
            'Lop-Holland Mix',
            'Pharaoh Hound Mix',
            'Bluetick Hound',
            'Labrador Retriever/Siberian Husky',
            'German Shepherd/Australian Cattle Dog',
            'Bluetick Hound Mix',
            'Dachshund Longhair',
            'Great Pyrenees/Chow Chow',
            'Catahoula/English Coonhound',
            'Mockingbird Mix',
            'Dogo Argentino/Labrador Retriever',
            'Great Pyrenees/Plott Hound',
            'Beagle/Chihuahua Shorthair',
            'Pointer/Queensland Heeler',
            'Australian Shepherd/Cocker Spaniel',
            'Bengal/Domestic Shorthair',
            'Chow Chow/Labrador Retriever',
            'Dogue De Bordeaux',
            'Irish Terrier Mix',
            'Pomeranian',
            'Australian Shepherd/Jack Russell Terrier',
            'Border Collie/Pembroke Welsh Corgi',
            'Bengal',
            'Chihuahua Shorthair/Yorkshire Terrier',
            'Jack Russell Terrier/Pit Bull',
            'Cornish Rex Mix',
            'Chihuahua Shorthair/Miniature Poodle',
            'Havanese Mix',
            'Dachshund Wirehair/Miniature Schnauzer',
            'Chihuahua Shorthair/Boston Terrier',
            'Boston Terrier/Australian Kelpie',
            'Catahoula',
            'German Shepherd/Anatol Shepherd',
            'Parakeet Mix',
            'Collie Rough/German Shepherd',
            'Border Collie/Shetland SheepDog',
            'Lowchen/Miniature Poodle',
            'Dachshund/Yorkshire Terrier',
            'Mastiff/Chinese Sharpei',
            'Chow Chow/German Shepherd',
            'Labrador Retriever/Chinese Sharpei',
            'Rabbit Sh',
            'Pit Bull/Carolina Dog',
            'Beauceron Mix',
            'Skye Terrier Mix',
            'West Highland',
            'Pit Bull/BullDog',
            'Australian Cattle Dog/Pointer',
            'Staffordshire/Boston Terrier',
            'Chinese Sharpei',
            'Manx Mix',
            'Australian Shepherd/Border Collie',
            'English Springer Spaniel Mix',
            'Chinese Sharpei/Basset Hound',
            'Chihuahua Longhair',
            'Domestic Medium Hair/Maine Coon',
            'Australian Shepherd/Beagle',
            'Cottontail Mix',
            'Vizsla',
            'Angora/Persian',
            'Shiba Inu Mix',
            'Bloodhound',
            'Dachshund/Pit Bull',
            'Labrador Retriever/Rottweiler',
            'Labrador Retriever/Whippet',
            'Dove Mix',
            'Chihuahua Shorthair/Miniature Schnauzer',
            'Pit Bull/Basset Hound',
            'Treeing Walker Coonhound/Labrador Retriever',
            'Weimaraner/Pit Bull',
            'Plott Hound',
            'Californian Mix',
            'Beagle/German Shepherd',
            'Chinese Sharpei/Labrador Retriever',
            'Papillon Mix',
            'Silky Terrier/Yorkshire Terrier',
            'Shih Tzu/Pit Bull',
            'Welsh Springer Spaniel',
            'Whippet/Labrador Retriever',
            'Wirehaired Pointing Griffon Mix',
            'Duck Mix',
            'Pit Bull/Catahoula',
            'Labrador Retriever/Miniature Poodle',
            'Dutch',
            'Bichon Frise',
            'Harrier',
            'British Shorthair Mix',
            'Great Pyrenees/Catahoula',
            'Cairn Terrier/Chihuahua Shorthair',
            'Whippet/Shetland SheepDog',
            'Boston Terrier/Pug',
            'Bullmastiff/Black Mouth Cur',
            'Yorkshire Terrier/Chihuahua Shorthair',
            'American Eskimo',
            'Pit Bull/Pointer',
            'Border Collie/Akita',
            'Yorkshire Terrier/Miniature Schnauzer',
            'Anatol Shepherd/Pit Bull',
            'West Highland Mix',
            'Dachshund/Miniature Pinscher',
            'Standard Schnauzer/Miniature Poodle',
            'Grackle',
            'Himalayan',
            'Welsh Terrier Mix',
            'Dachshund/English BullDog',
            'Harrier/Labrador Retriever',
            'Doberman Pinsch/Catahoula',
            'Border Terrier/Soft Coated Wheaten Terrier',
            'German Shepherd/Chow Chow',
            'Italian Greyhound Mix',
            'Australian Kelpie/Pit Bull',
            'Gerbil Mix',
            'Great Pyrenees/American BullDog',
            'Abyssinian Mix',
            'Mastiff/Pit Bull',
            'Dachshund/Norfolk Terrier',
            'Labrador Retriever/American BullDog',
            'Miniature Poodle/Maltese',
            'Pointer/Jack Russell Terrier',
            'Bruss Griffon Mix',
            'Lizard',
            'Catahoula/American Pit Bull Terrier',
            'Cardigan Welsh Corgi/German Shepherd',
            'Beagle/Jack Russell Terrier',
            'Rat Mix',
            'Australian Cattle Dog/Chinese Sharpei',
            'English Shepherd Mix',
            'Great Pyrenees/Anatol Shepherd',
            'Bull Terrier/Jack Russell Terrier',
            'Chihuahua Shorthair/Pug',
            'Neapolitan Mastiff Mix',
            'German Shepherd/Collie Rough',
            'Exotic Shorthair Mix',
            'Shih Tzu/Chihuahua Shorthair',
            'Standard Schnauzer/Border Terrier',
            'Rat Terrier/Miniature Poodle',
            'Alaskan Husky',
            'English Springer Spaniel/Beagle',
            'Boxer/American BullDog',
            'Boston Terrier/Miniature Schnauzer',
            'Jack Russell Terrier/Italian Greyhound',
            'German Shepherd/Siberian Husky',
            'Border Terrier/Yorkshire Terrier',
            'Pit Bull/St. Bernard Smooth Coat',
            'Catahoula/Pointer',
            'Pug/Labrador Retriever',
            'American Pit Bull Terrier',
            'Labrador Retriever/Golden Retriever',
            'Turkey Mix',
            'Border Collie/Pit Bull',
            'Pointer/Dalmatian',
            'Australian Cattle Dog/Black Mouth Cur',
            'German Shepherd/Australian Kelpie',
            'Snake',
            'Rottweiler/German Shepherd',
            'Labrador Retriever/American Staffordshire Terrier',
            'Bulldog/Pit Bull',
            'Beagle/Basset Hound',
            'Collie Rough/Australian Shepherd',
            'Bombay Mix',
            'Chihuahua Shorthair/Pomeranian',
            'Black Mouth Cur/Dachshund',
            'Cairn Terrier/Miniature Schnauzer',
            'Cavalier Span/Border Collie',
            'Beagle/Pug',
            'Chihuahua Shorthair/Miniature Pinscher',
            'Dachshund Wirehair/Miniature Poodle',
            'Chicken',
            'Alaskan Malamute Mix',
            'Border Collie/Labrador Retriever',
            'Collie Smooth/Boxer',
            'Queensland Heeler/Pointer',
            'Cocker Spaniel/Chihuahua Shorthair',
            'Jack Russell Terrier/Miniature Poodle',
            'Norfolk Terrier/Yorkshire Terrier',
            'Pit Bull/Australian Cattle Dog',
            'Chihuahua Shorthair/Cardigan Welsh Corgi',
            'Tarantula',
            'Alaskan Malamute',
            'Treeing Walker Coonhound/German Shepherd',
            'Boxer/Jack Russell Terrier',
            'Standard Poodle Mix',
            'Jack Russell Terrier/Border Collie',
            'Soft Coated Wheaten Terrier/Chihuahua Shorthair',
            'Australian Cattle Dog/Bloodhound',
            'Bichon Frise/Miniature Poodle',
            'Pug',
            'Anatol Shepherd/German Shepherd',
            'Hamster Mix',
            'Mastiff',
            'Great Pyrenees/Standard Poodle',
            'Miniature Poodle/Cairn Terrier',
            'Bull Terrier/Boxer',
            'Siamese/Domestic Shorthair',
            'Yorkshire Terrier/Havanese',
            'Pembroke Welsh Corgi/Chihuahua Shorthair',
            'Canaan Dog/Pit Bull',
            'Border Collie/Parson Russell Terrier',
            'Boykin Span',
            'Budgerigar',
            'Kuvasz/Labrador Retriever',
            'Chow Chow/Pit Bull',
            'Pit Bull/Mastiff',
            'Presa Canario Mix',
            'Chow Chow/Australian Cattle Dog',
            'Pbgv/Jack Russell Terrier',
            'Cairn Terrier/Border Terrier',
            'Jack Russell Terrier/Unknown',
            'Pit Bull/Border Terrier',
            'Maine Coon',
            'Finch',
            'Blue Lacy/American BullDog',
            'Picardy SheepDog',
            'Rex',
            'Siberian Husky/German Shepherd',
            'Pointer/Australian Cattle Dog',
            'Doberman Pinsch/Vizsla',
            'German Pinscher/Whippet',
            'Catahoula/German Shepherd',
            'Border Terrier/Miniature Poodle',
            'Kuvasz Mix',
            'Alaskan Malamute/Border Collie',
            'Labrador Retriever/Great Pyrenees',
            'Pit Bull/Chihuahua Shorthair',
            'Pit Bull/Labrador Retriever',
            'Ferret Mix',
            'German Shepherd/Rottweiler',
            'Rat Terrier/Dachshund',
            'Greater Swiss Mountain Dog Mix',
            'Labrador Retriever/Black Mouth Cur',
            'Norfolk Terrier',
            'Redbone Hound/Dachshund',
            'Afghan Hound/Labrador Retriever',
            'Australian Cattle Dog/American Staffordshire Terrier',
            'Black/Tan Hound/Black Mouth Cur',
            'Australian Cattle Dog/Collie Rough',
            'Boxer/Great Dane',
            'Cold Water',
            'Finnish Spitz Mix',
            'Brittany',
            'Chihuahua Shorthair/Pit Bull',
            'Chinese Sharpei/Pointer',
            'Labrador Retriever/Mastiff',
            'Wire Hair Fox Terrier',
            'Great Pyrenees/Border Collie',
            'Australian Cattle Dog/Akita',
            'Turtle',
            'Manx/Siamese',
            'American Foxhound Mix',
            'Yorkshire Terrier/Miniature Poodle',
            'Vizsla/Labrador Retriever',
            'Devon Rex Mix',
            'German Shepherd/Alaskan Husky',
            'St. Bernard Rough Coat/Boxer',
            'Rhod Ridgeback/Labrador Retriever',
            'Australian Shepherd/Anatol Shepherd',
            'Pit Bull/Queensland Heeler',
            'Welsh Springer Spaniel/Labrador Retriever',
            'Labrador Retriever/Harrier',
            'Chihuahua Shorthair/Basset Hound',
            'Beagle/Australian Cattle Dog',
            'Anatol Shepherd/Labrador Retriever',
            'Cardigan Welsh Corgi/Australian Shepherd',
            'Boxer/Boston Terrier',
            'Yorkshire Terrier/Border Terrier',
            'Australian Cattle Dog/Treeing Walker Coonhound',
            'West Highland/Miniature Poodle',
            'Australian Cattle Dog/Boxer',
            'Feist Mix',
            'Boerboel',
            'Chihuahua Shorthair/Beagle',
            'Havana Mix',
            'Jack Russell Terrier/Beagle',
            'Dachshund/Catahoula',
            'Miniature Poodle/American Eskimo',
            'Old English Bulldog Mix',
            'West Highland/Cairn Terrier',
            'Flat Coat Retriever/Pit Bull',
            'Australian Cattle Dog/Plott Hound',
            'Domestic Shorthair/Abyssinian',
            'Lhasa Apso/Border Terrier',
            'Pit Bull/German Shepherd',
            'Rottweiler/Rhod Ridgeback',
            'Standard Schnauzer Mix',
            'Dalmatian/Pit Bull',
            'Norfolk Terrier/Bruss Griffon',
            'Cairn Terrier/Border Collie',
            'Maltese/Dalmatian',
            'Golden Retriever/Chow Chow',
            'Bruss Griffon/Pug',
            'Bullmastiff Mix',
            'Manchester Terrier/Jack Russell Terrier',
            'Blue Lacy/Collie Smooth',
            'Labrador Retriever/Catahoula',
            'Rat Terrier/Cardigan Welsh Corgi',
            'Labrador Retriever/Black/Tan Hound',
            'Dachshund Wirehair/Chihuahua Shorthair',
            'Redbone Hound/Redbone Hound',
            'Tibetan Terrier Mix',
            'Flat Coat Retriever/Golden Retriever',
            'Black Mouth Cur/Mastiff',
            'Norwich Terrier',
            'English Spot',
            'Pit Bull/Border Collie',
            'Parson Russell Terrier/Chihuahua Shorthair',
            'Australian Cattle Dog/Border Collie',
            'Rottweiler/Siberian Husky',
            'French Bulldog Mix',
            'Jack Russell Terrier/Manchester Terrier',
            'Weimaraner/Labrador Retriever',
            'Siberian Husky/Border Collie',
            'Miniature Schnauzer/Chihuahua Longhair',
            'Cardigan Welsh Corgi/Pointer',
            'Border Collie/Australian Cattle Dog',
            'Field Spaniel/Cocker Spaniel',
            'Smooth Fox Terrier/Basenji',
            'Shetland Sheepdog/Border Collie',
            'Lhasa Apso/Cairn Terrier',
            'Field Spaniel Mix',
            'Jack Russell Terrier/Dachshund',
            'American Staffordshire Terrier/Jack Russell Terrier',
            'Akita',
            'Picardy Sheepdog Mix',
            'Golden Retriever/Labrador Retriever',
            'Miniature Schnauzer/Border Collie',
            'Blue Lacy/Pointer',
            'Shih Tzu/Cocker Spaniel',
            'Labrador Retriever/Akita',
            'Pembroke Welsh Corgi/Australian Cattle Dog',
            'Boston Terrier/Chihuahua Shorthair',
            'Beagle/Catahoula',
            'Dachshund/Harrier',
            'Jindo/Shiba Inu',
            'Australian Cattle Dog/American Pit Bull Terrier',
            'Pit Bull/Weimaraner',
            'Golden Retriever/Great Pyrenees',
            'Border Terrier/Rat Terrier',
            'Australian Shepherd',
            'Miniature Schnauzer/Yorkshire Terrier',
            'Chihuahua Shorthair/Finnish Spitz',
            'Boxer/Labrador Retriever',
            'Beagle/Dachshund',
            'Border Collie/Jack Russell Terrier',
            'Labrador Retriever/Redbone Hound',
            'Cavalier Span',
            'Cocker Spaniel/Chihuahua Longhair',
            'Shih Tzu/Maltese',
            'Great Pyrenees/English Setter',
            'Golden Retriever/Dachshund',
            'Border Collie/Chow Chow',
            'Chihuahua Shorthair/Papillon',
            'Golden Retriever/Pembroke Welsh Corgi',
            'Collie Smooth/German Shepherd',
            'Cocker Spaniel/Pembroke Welsh Corgi',
            'Shiba Inu/Siberian Husky',
            'Basset Hound/Labrador Retriever',
            'Carolina Dog/Border Collie',
            'Border Collie/Basenji',
            'Persian',
            'Fox',
            'Canaan Dog Mix',
            'Dachshund/Pug',
            'Black Mouth Cur/Australian Cattle Dog',
            'Dalmatian/Labrador Retriever',
            'Shih Tzu/Yorkshire Terrier',
            'Chihuahua Shorthair/Smooth Fox Terrier',
            'Ferret',
            'Pekingese/Pug',
            'German Shepherd/Cardigan Welsh Corgi',
            'Boxer/Chinese Sharpei',
            'English Setter Mix',
            'Toy Poodle/Yorkshire Terrier',
            'Border Terrier/Dachshund',
            'Boykin Span Mix',
            'Pointer/Staffordshire',
            'Pointer/Collie Smooth',
            'German Shepherd/Border Collie',
            'Catahoula/Treeing Walker Coonhound',
            'Basenji/Labrador Retriever',
            'Miniature Poodle/Lhasa Apso',
            'Dogue De Bordeaux/Labrador Retriever',
            'Old English SheepDog',
            'Basenji/Chihuahua Shorthair',
            'Pekingese/Shih Tzu',
            'Newfoundland/Great Pyrenees',
            'Plott Hound/Rottweiler',
            'Border Collie/Staffordshire',
            'Irish Wolfhound Mix',
            'Chihuahua Shorthair/Shetland SheepDog',
            'Rhod Ridgeback/Australian Cattle Dog',
            'Pit Bull/Boston Terrier',
            'Dalmatian',
            'Shih Tzu/Miniature Poodle',
            'Jack Russell Terrier/Pug',
            'Collie Smooth/Beagle',
            'American Bulldog/Boxer',
            'Great Dane/Mastiff',
            'Chihuahua Shorthair/Basenji',
            'American Pit Bull Terrier/American Pit Bull Terrier',
            'Australian Shepherd/Cardigan Welsh Corgi',
            'Staffordshire/English BullDog',
            'Basset Hound/Australian Shepherd',
            'Pug/Border Terrier',
            'Podengo Pequeno Mix',
            'Australian Shepherd/Boxer',
            'Australian Cattle Dog/Pug',
            'Dachshund Longhair/Pomeranian',
            'Staffordshire/Basset Hound',
            'Schipperke Mix',
            'Chihuahua Shorthair/Pembroke Welsh Corgi',
            'Australian Cattle Dog/Australian Shepherd',
            'Boxer/BullDog',
            'Pig Mix',
            'Staffordshire',
            'Labrador Retriever/Anatol Shepherd'
            'Newfoundland/Australian Cattle Dog',
            ]
        
    def animal_type(self):
        return ['----------','Cat','Dog','Bird','Livestock','Other']
